### ISSUE TITLE
Bug in the README

### ISSUE THREAD

**Issue by bihor** [b13/uniquealiasmapper#5]
Hello, I think there is an error in the manual. Here:
`_arguments:
      addressid: partneralias`
it should be this way:
`_arguments:
      partneralias: addressid`
You could add a more complex example too:
`routeEnhancers:
  MyextPlugin:
    type: Extbase
    limitToPages: [24]
    extension: Myext
    plugin: Pi1
    routes:
      - { routePath: '/eintrag/{myext_title}', _controller: 'Content::show', _arguments: {'myext_title': 'content'} }
    aspects:
      myext_title:
        type: UniqueAlias
        tableName: 'tx_myext_domain_model_content'
        aliasField: 'title'
        expires: '15d'
        uniqueConfiguration:
          fallbackCharacter: '-'`

**Comment by bmack** [comment]
Hey @bihor ,

can you create a PR for this?

**Comment by bihor** [comment]
Pull request created.
